---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  requirements:
    cpu:
      # required as this preference uses SocketsCoresThreads with a ratio of
      # 4, 1:4:2 == 8 vCPUs
      guest: 8
    memory:
      guest: 1.5Gi
