---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
  labels:
    instancetype.kubevirt.io/required-cpu: "8"
    instancetype.kubevirt.io/required-memory: "1.5Gi"
spec:
  requirements:
    cpu:
      # required as this preference uses SocketsCoresThreads with a ratio of
      # 4, 1:4:2 == 8 vCPUs
      guest: 8
    memory:
      guest: 1.5Gi
