---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

nameSuffix: .micro

patches:
  - path: micro.yaml
    target:
      kind: VirtualMachineInstancetype
  - path: micro.yaml
    target:
      kind: VirtualMachineClusterInstancetype
