---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

nameSuffix: .medium

patches:
  - path: medium.yaml
    target:
      kind: VirtualMachineInstancetype
  - path: medium.yaml
    target:
      kind: VirtualMachineClusterInstancetype
