---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
  labels:
    instancetype.kubevirt.io/required-cpu: "1"
    instancetype.kubevirt.io/required-memory: "1.5Gi"
spec:
  # https://access.redhat.com/articles/rhel-limits#minimum-required-memory-3
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 1.5Gi
