---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  # https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc755116(v=ws.10)#system-requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 512Mi
