---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../1

patches:
  - target:
      kind: VirtualMachineClusterInstancetype
    patch: |-
      - op: replace
        path: /kind
        value: VirtualMachineInstancetype
