# golangci configuration
# Taken from https://github.com/kubevirt/kubevirt/blob/main/.golangci.yml
# and additionally ginkgolinter was enabled.

version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - ginkgolinter
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - paramTypeCombine
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 1024
        rangeValCopy:
          sizeThreshold: 1024
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-functions:
        - ^Eventually$
        - ^EventuallyWithOffset$
        - ^ExpectWithOffset$
        - ^console\.ExpectBatch$
        - ^console\.RunCommand$
    nolintlint:
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped
      allow-unused: false # report any unused nolint directives
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
      checks:
        - all
        - "-QF1001" # exclude 'could apply De Morgan's law'
        - "-QF1008" # exclude 'could remove embedded field "<field>" from selector'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: checks.SkipTestIfNoCPUManager'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - kubevirt.io/kubevirt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
