---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachineInstancetype
metadata:
  name: VirtualMachineInstancetype
  labels:
    kubevirt.io/size: tiny
spec:
  cpu:
    guest: 1
  memory:
    guest: 1Gi
