---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: required-architecture
  labels:
    instancetype.kubevirt.io/required-architecture: "amd64"
spec:
  requirements:
    architecture: "amd64"
