---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
  labels:
    instancetype.kubevirt.io/required-cpu: "1"
    instancetype.kubevirt.io/required-memory: "256Mi"
spec:
  # https://github.com/cirros-dev/cirros/issues/53
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 256Mi
