---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

nameSuffix: .large

patches:
  - path: large.yaml
    target:
      kind: VirtualMachineInstancetype
  - path: large.yaml
    target:
      kind: VirtualMachineClusterInstancetype
