---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
  labels:
    instancetype.kubevirt.io/required-cpu: "1"
    instancetype.kubevirt.io/required-memory: "2Gi"
spec:
  # https://documentation.suse.com/sles/15-SP6/html/SLES-all/cha-x86.html#sec-x86-requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
