---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
  labels:
    instancetype.kubevirt.io/required-cpu: "1"
    instancetype.kubevirt.io/required-memory: "2Gi"
spec:
  # https://learn.microsoft.com/en-us/windows-server/get-started/hardware-requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
