---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachinePreference
metadata:
  name: metadata
  annotations:
    tags: "hidden,kubevirt,linux,centos-stream"
    iconClass: "icon-centos"
