---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

nameSuffix: .4xlarge

patches:
  - path: 4xlarge.yaml
    target:
      kind: VirtualMachineInstancetype
  - path: 4xlarge.yaml
    target:
      kind: VirtualMachineClusterInstancetype
