---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: metadata
  annotations:
    openshift.io/display-name: "Microsoft Windows Server 2012/2012 R2 (virtio)"
