---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
  labels:
    instancetype.kubevirt.io/required-cpu: "1"
    instancetype.kubevirt.io/required-memory: "512Mi"
spec:
  # https://wiki.alpinelinux.org/wiki/Requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 512Mi
