#!/bin/bash

# yamllint requires the initial `---` in the file but this isn't generated by kustomize
echo "---" > common-instancetypes-all-bundle.yaml
kustomize build >> common-instancetypes-all-bundle.yaml

echo "---" > common-instancetypes-bundle.yaml
kustomize build VirtualMachineInstancetypes >> common-instancetypes-bundle.yaml

echo "---" > common-clusterinstancetypes-bundle.yaml
kustomize build VirtualMachineClusterInstancetypes >> common-clusterinstancetypes-bundle.yaml

echo "---" > common-preferences-bundle.yaml
kustomize build VirtualMachinePreferences >> common-preferences-bundle.yaml

echo "---" > common-clusterpreferences-bundle.yaml
kustomize build VirtualMachineClusterPreferences >> common-clusterpreferences-bundle.yaml
