---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ./metadata
  - ./requirements
  - ../../../components/preferred-architecture/arm64
  - ../../../components/required-architecture/arm64
  - ../../../components/disk-dedicatediothread

nameSuffix: ".9.arm64"
