---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
  labels:
    instancetype.kubevirt.io/required-cpu: "2"
    instancetype.kubevirt.io/required-memory: "4Gi"
spec:
  # https://www.microsoft.com/en-gb/windows/windows-11-specifications?r=1
  requirements:
    cpu:
      guest: 2
    memory:
      guest: 4Gi
