---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  # https://web.archive.org/web/20210318063910/https://support.microsoft.com/en-us/windows/windows-7-system-requirements-df0900f2-3513-a851-13e7-0d50bc24e15f
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
