---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ./metadata
  - ./requirements
  - ../../../components/disk-dedicatediothread
  - ../../../components/rng

nameSuffix: ".9.s390x"
